services:
  - type: web
    name: cervibot
    env: python
    rootDir: cerviBOT
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 8000
      - key: RELOAD
        value: false

